# Generated by Django 4.2 on 2023-08-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('fathername', models.CharField(max_length=10, verbose_name='fathername')),
                ('Class', models.CharField(max_length=10, verbose_name='class')),
                ('age', models.IntegerField(max_length=10, verbose_name='age')),
                ('image', models.ImageField(upload_to='', verbose_name='file')),
            ],
        ),
    ]
